return {
	-- "folke/flash.nvim",
	-- event = "VeryLazy",
	-- ---@type Flash.Config
	-- opts = {
	-- 	modes = {
	-- 		search = {
	-- 			enabled = true,
	-- 		},
	-- 		char = {
	-- 			jump_labels = true,
	-- 		},
	-- 	},
	-- },
	-- keys = function(_, keys)
	-- 	-- filter out any keymap that uses "R"
	-- 	return vim.tbl_filter(function(keymap)
	-- 		return keymap[1] ~= "R"
	-- 	end, keys)
	-- end,
	--  -- stylua: ignore
	--  keys = {
	--    { "s", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Flash" },
	--    { "S", mode = { "n", "x", "o" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
	--    { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
	--    { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
	--
	--    { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
	--  },
}
