-- nvim-cmp source for GLSL struct field completion (`varName.<field>`).
--
-- Mirrors the workspace's web-editor completion at
--   src/components/editor/structFieldCompletions.ts
-- so the same struct catalog drives both editors.
--
-- Data source:  ~/.config/nvim/snippets/glsl-structs.json
-- Generated by: `pnpm snippets:install` in the glsl-workspace repo
-- Registry src: src/lib/shader-imports-structs.ts
--
-- How it works at the cursor:
--   1. Trigger on `.`
--   2. Grab text up to the cursor — must end with `<word>.<partial>`
--   3. Scan the buffer above the cursor for `<TypeName> <word>` followed by
--      `=`, `;`, `,`, or `)`  → that's the declaration of `<word>`
--   4. Look up TypeName in the loaded struct map, return its fields
--   5. Otherwise return empty — other cmp sources still show their items

local M = {}

local STRUCTS_PATH = vim.fn.expand("~/.config/nvim/snippets/glsl-structs.json")
local _structs = nil

local function load_structs()
  if _structs ~= nil then return _structs end
  local f = io.open(STRUCTS_PATH, "r")
  if not f then
    _structs = {}
    return _structs
  end
  local raw = f:read("*all")
  f:close()
  local ok, parsed = pcall(vim.json.decode, raw)
  _structs = (ok and type(parsed) == "table") and parsed or {}
  return _structs
end

-- Hot-reload when the JSON gets rewritten by `pnpm snippets:install`
vim.api.nvim_create_autocmd({ "BufWritePost", "FileChangedShellPost" }, {
  pattern = STRUCTS_PATH,
  callback = function() _structs = nil end,
})

function M.new()
  return setmetatable({}, { __index = M })
end

function M:is_available()
  local ft = vim.bo.filetype
  return ft == "glsl" or ft == "frag" or ft == "vert" or ft == "comp"
end

function M:get_trigger_characters()
  return { "." }
end

function M:get_keyword_pattern()
  -- Match field names so cmp keeps the popup open while you type
  return [[\k\+]]
end

-- Scan lines above the cursor (last match wins for shadowing) to find a
-- declaration like `<TypeName> <var_name>[=;,)]`.
local function find_var_type(bufnr, var_name, cursor_line)
  -- nvim_buf_get_lines is 0-indexed; cursor_line is 1-indexed → use as end-exclusive
  local lines = vim.api.nvim_buf_get_lines(bufnr, 0, cursor_line, false)
  local pattern = "(%w+)%s+" .. var_name .. "%s*[%=%;%,%)]"
  local last_type = nil
  for _, line in ipairs(lines) do
    for t in line:gmatch(pattern) do
      last_type = t
    end
  end
  return last_type
end

function M:complete(request, callback)
  local before = request.context.cursor_before_line
  local var, _partial = before:match("([%a_][%w_]*)%.(%w*)$")
  if not var then
    callback({ items = {}, isIncomplete = false })
    return
  end

  local bufnr = vim.api.nvim_get_current_buf()
  local cursor_line = request.context.cursor.line + 1 -- 0-indexed → 1-indexed
  local type_name = find_var_type(bufnr, var, cursor_line)
  if not type_name then
    callback({ items = {}, isIncomplete = false })
    return
  end

  local structs = load_structs()
  local info = structs[type_name]
  if not info or not info.fields then
    callback({ items = {}, isIncomplete = false })
    return
  end

  local kinds = vim.lsp.protocol.CompletionItemKind
  local items = {}
  for _, field in ipairs(info.fields) do
    local detail = field.type
    if field.detail and field.detail ~= "" then
      detail = field.type .. " — " .. field.detail
    end
    table.insert(items, {
      label = field.name,
      kind = kinds.Field,
      detail = detail,
      documentation = {
        kind = "markdown",
        value = string.format(
          "**`%s`** (%s · `%s`)\n\n%s",
          field.name,
          type_name,
          field.type,
          field.detail or ""
        ),
      },
    })
  end

  callback({ items = items, isIncomplete = false })
end

return M
